# Generated by Django 3.1.7 on 2021-02-20 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('PK_Brand', models.AutoField(db_column='PK_Brand', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nameBrand', max_length=100)),
            ],
            options={
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('PK_Category', models.AutoField(db_column='PK_Category', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nameCategory', max_length=100)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('PK_Tent', models.AutoField(db_column='PK_Tent', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nameTent', max_length=200)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=15)),
                ('weight', models.DecimalField(db_column='weight', decimal_places=2, max_digits=3)),
                ('places', models.IntegerField(db_column='places')),
                ('doors', models.IntegerField(db_column='doors')),
                ('windows', models.IntegerField(db_column='windows')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('imagepath', models.ImageField(blank=True, db_column='imagePath', max_length=255, null=True, upload_to='')),
                ('PK_Brand', models.ForeignKey(db_column='PK_Brand', on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.brand')),
                ('PK_Category', models.ForeignKey(db_column='PK_Category', on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.category')),
            ],
            options={
                'db_table': 'Tent',
            },
        ),
    ]
