# Generated by Django 3.1.7 on 2021-04-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tent',
            name='imagepath',
            field=models.ImageField(blank=True, db_column='imagePath', max_length=255, null=True, upload_to='C:\\Users\\hunte\\Desktop\\mysite\\media'),
        ),
    ]
